const fs = require('fs');
const path = 'src/pages/ServiceOrders/ServiceOrdersPage.tsx';
let content = fs.readFileSync(path, 'utf8');
const pattern = / {6}<Card\.Container>[\s\S]*? {6}<\/Card\.Container>/;
const replacement = `      <Card.Container>\n        {serviceOrdersData.map((serviceOrder: Orcamento) => {\n          const statusValue = normalizeStatus(serviceOrder.status);\n          return (\n            <Card\n              className="capitalize"\n              key={serviceOrder.id ?? serviceOrder.placa}\n              onClick={() => handleCardClick(serviceOrder)}>\n              {serviceOrder.created_at && isToday(new Date(serviceOrder.created_at)) && (\n                <Card.Badge></Card.Badge>\n              )}\n              <Card.Header\n                title={serviceOrder.descricao || \`Orçamento ${serviceOrder.id ?? serviceOrder.placa}\`}\n                description={\`Cliente: ${serviceOrder.cliente_id || 'Não identificado'}\`}\n              />\n              <Card.Content>\n                <div className="flex flex-col gap-3">\n                  <div className="flex justify-between items-center">\n                    <div className="flex items-center gap-2">\n                      <span className="text-xs text-muted-foreground">Placa</span>\n                      <CarPlate plate={serviceOrder.placa || ''} />\n                    </div>\n                    <StatusDropDown\n                      value={statusValue}\n                      options={SO_STATUS_LIST}\n                      disabled={true}\n                      onChange={() => {}}\n                    />\n                  </div>\n                  <div className="flex justify-between text-sm text-muted-foreground">\n                    <span>Entrada: {serviceOrder.data_entrada || '-'}</span>\n                    <span>Prazo: {serviceOrder.data_prazo || '-'}</span>\n                    <span>\n                      Criado: {serviceOrder.created_at ? timestampToLocaleString(new Date(serviceOrder.created_at).getTime()) : '-'}\n                    </span>\n                  </div>\n                  <p className="text-sm text-muted-foreground line-clamp-2">\n                    {serviceOrder.observacao || serviceOrder.comentario_cliente || 'Sem observações'}\n                  </p>\n                </div>\n              </Card.Content>\n            </Card>\n          );\n        })}\n      </Card.Container>`;
if (!pattern.test(content)) {
  console.error('pattern not found');
  process.exit(1);
}
content = content.replace(pattern, replacement);
fs.writeFileSync(path, content, 'utf8');
